/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.clicsistemas.VirtualSocket.gui.controls;

import com.clicsistemas.VirtualSocket.gui.PortDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author marcelo
 */
public class ConnDetailsControl extends javax.swing.JPanel {
    private IConnControl control;

    /**
     * Creates new form ConnectionControl
     */
    public ConnDetailsControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtHostname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spPort = new javax.swing.JSpinner();
        btnComPorts = new javax.swing.JButton();
        btnConnect = new javax.swing.JButton();
        chkSecure = new javax.swing.JCheckBox();
        chkUDp = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Connection/Server "));

        jLabel1.setText("Hostname or IP Addres:");

        txtHostname.setText("0.0.0.0");

        jLabel2.setText("Port");

        spPort.setModel(new javax.swing.SpinnerNumberModel(0, 0, 65535, 1));

        btnComPorts.setText("Standard Ports");
        btnComPorts.setActionCommand("Standard Ports");
        btnComPorts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComPortsActionPerformed(evt);
            }
        });

        btnConnect.setText("Connect to");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        chkSecure.setText("Secure?");

        chkUDp.setText("Use UDP instead TCP?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(chkSecure)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(chkUDp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnConnect))
                        .addComponent(txtHostname))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(spPort)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 53, Short.MAX_VALUE)
                        .addComponent(btnComPorts)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComPorts)
                    .addComponent(btnConnect)
                    .addComponent(chkUDp)
                    .addComponent(chkSecure))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnComPortsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComPortsActionPerformed
        PortDialog dia = new PortDialog((JFrame) SwingUtilities.getWindowAncestor(this), PortDialog.TCP);
        dia.setVisible(true);
    }//GEN-LAST:event_btnComPortsActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        if(this.control != null) {
            this.control.OnClickConnect();
        }
    }//GEN-LAST:event_btnConnectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComPorts;
    private javax.swing.JButton btnConnect;
    private javax.swing.JCheckBox chkSecure;
    private javax.swing.JCheckBox chkUDp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner spPort;
    private javax.swing.JTextField txtHostname;
    // End of variables declaration//GEN-END:variables

    public String getHostName() {
        return this.txtHostname.getText();
    }
    
    public int getPort() {
        return (Integer)this.spPort.getValue();
    }
    
    public boolean isSecureEnabled() {
        return this.chkSecure.isSelected();
    }
    
    public boolean isUdpEnabled() {
        return this.chkUDp.isSelected();
    }
    
    public void setConnectButtonText(String text) {
        this.btnConnect.setText(text);
    }
    
    public void setSecureVisible(boolean visible) {
        this.chkSecure.setVisible(visible);
    }
    
    public void setListener(IConnControl control) {
        this.control = control;
    }
}
